// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package consumerappmock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/t5mx27dp/consumerapp/message"
)

// NewConsumer creates a new instance of Consumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Consumer {
	mock := &Consumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Consumer is an autogenerated mock type for the Consumer type
type Consumer struct {
	mock.Mock
}

type Consumer_Expecter struct {
	mock *mock.Mock
}

func (_m *Consumer) EXPECT() *Consumer_Expecter {
	return &Consumer_Expecter{mock: &_m.Mock}
}

// Consume provides a mock function for the type Consumer
func (_mock *Consumer) Consume(ctx context.Context, queue message.Queue) (<-chan message.Message, error) {
	ret := _mock.Called(ctx, queue)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 <-chan message.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, message.Queue) (<-chan message.Message, error)); ok {
		return returnFunc(ctx, queue)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, message.Queue) <-chan message.Message); ok {
		r0 = returnFunc(ctx, queue)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan message.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, message.Queue) error); ok {
		r1 = returnFunc(ctx, queue)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Consumer_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type Consumer_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
//   - queue message.Queue
func (_e *Consumer_Expecter) Consume(ctx interface{}, queue interface{}) *Consumer_Consume_Call {
	return &Consumer_Consume_Call{Call: _e.mock.On("Consume", ctx, queue)}
}

func (_c *Consumer_Consume_Call) Run(run func(ctx context.Context, queue message.Queue)) *Consumer_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 message.Queue
		if args[1] != nil {
			arg1 = args[1].(message.Queue)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Consumer_Consume_Call) Return(messageCh <-chan message.Message, err error) *Consumer_Consume_Call {
	_c.Call.Return(messageCh, err)
	return _c
}

func (_c *Consumer_Consume_Call) RunAndReturn(run func(ctx context.Context, queue message.Queue) (<-chan message.Message, error)) *Consumer_Consume_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function for the type Consumer
func (_mock *Consumer) GetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Consumer_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type Consumer_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *Consumer_Expecter) GetName() *Consumer_GetName_Call {
	return &Consumer_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *Consumer_GetName_Call) Run(run func()) *Consumer_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Consumer_GetName_Call) Return(s string) *Consumer_GetName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Consumer_GetName_Call) RunAndReturn(run func() string) *Consumer_GetName_Call {
	_c.Call.Return(run)
	return _c
}
