// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package messagemock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMessage creates a new instance of Message. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Message {
	mock := &Message{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Message is an autogenerated mock type for the Message type
type Message struct {
	mock.Mock
}

type Message_Expecter struct {
	mock *mock.Mock
}

func (_m *Message) EXPECT() *Message_Expecter {
	return &Message_Expecter{mock: &_m.Mock}
}

// Ack provides a mock function for the type Message
func (_mock *Message) Ack() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ack")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Message_Ack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ack'
type Message_Ack_Call struct {
	*mock.Call
}

// Ack is a helper method to define mock.On call
func (_e *Message_Expecter) Ack() *Message_Ack_Call {
	return &Message_Ack_Call{Call: _e.mock.On("Ack")}
}

func (_c *Message_Ack_Call) Run(run func()) *Message_Ack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Message_Ack_Call) Return(err error) *Message_Ack_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Message_Ack_Call) RunAndReturn(run func() error) *Message_Ack_Call {
	_c.Call.Return(run)
	return _c
}

// GetBody provides a mock function for the type Message
func (_mock *Message) GetBody() []byte {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBody")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// Message_GetBody_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBody'
type Message_GetBody_Call struct {
	*mock.Call
}

// GetBody is a helper method to define mock.On call
func (_e *Message_Expecter) GetBody() *Message_GetBody_Call {
	return &Message_GetBody_Call{Call: _e.mock.On("GetBody")}
}

func (_c *Message_GetBody_Call) Run(run func()) *Message_GetBody_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Message_GetBody_Call) Return(bytes []byte) *Message_GetBody_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *Message_GetBody_Call) RunAndReturn(run func() []byte) *Message_GetBody_Call {
	_c.Call.Return(run)
	return _c
}

// Nack provides a mock function for the type Message
func (_mock *Message) Nack() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Nack")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Message_Nack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Nack'
type Message_Nack_Call struct {
	*mock.Call
}

// Nack is a helper method to define mock.On call
func (_e *Message_Expecter) Nack() *Message_Nack_Call {
	return &Message_Nack_Call{Call: _e.mock.On("Nack")}
}

func (_c *Message_Nack_Call) Run(run func()) *Message_Nack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Message_Nack_Call) Return(err error) *Message_Nack_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Message_Nack_Call) RunAndReturn(run func() error) *Message_Nack_Call {
	_c.Call.Return(run)
	return _c
}

// Requeue provides a mock function for the type Message
func (_mock *Message) Requeue() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Requeue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Message_Requeue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Requeue'
type Message_Requeue_Call struct {
	*mock.Call
}

// Requeue is a helper method to define mock.On call
func (_e *Message_Expecter) Requeue() *Message_Requeue_Call {
	return &Message_Requeue_Call{Call: _e.mock.On("Requeue")}
}

func (_c *Message_Requeue_Call) Run(run func()) *Message_Requeue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Message_Requeue_Call) Return(err error) *Message_Requeue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Message_Requeue_Call) RunAndReturn(run func() error) *Message_Requeue_Call {
	_c.Call.Return(run)
	return _c
}
